---
###
# Deploying tasks
- name: Clone application GIT repo
  git:
    repo: '{{item}}'
    dest: /var/www/html/{{ project }}/
    update: yes
    force: yes
    recursive: yes
    accept_hostkey: yes
    track_submodules: no
  run_once: true
  with_items:
    - "{{project_repos}}"

- name: Configure application permissions after cloning
  file:
    path: /var/www/html/{{ project }}/
    owner: www-data
    group: www-data
    recurse: yes

#- name: Change default DocumentRoot
#  lineinfile:
#    dest: /etc/apache2/sites-available/000-default.conf
#    regexp: '^        DocumentRoot /var/www/html$'
#    line: '        DocumentRoot /var/www/html/{{ project }}'
#  notify:
#    - restart_apache
