---
- name: install apache2
  apt: 
    name: apache2 
    update_cache: yes 
    state: latest

- name: enabled mod_rewrite
  apache2_module: 
    name: rewrite
    state: present
  notify:
  - restart_apache

- name: apache2 listen on port {{ http_port }}
  lineinfile: 
    dest: /etc/apache2/ports.conf 
    regexp: '^Listen ' 
    line: 'Listen {{ http_port }}'
    state: present
  notify:
  - restart_apache

- name: apache2 virtualhost on port {{ http_port }}
  lineinfile: 
    dest: /etc/apache2/sites-available/000-default.conf 
    regexp: '^<VirtualHost \*:'
    line: '<VirtualHost *:{{ http_port }}>'
  notify:
  - restart_apache
