---
- name: Check firewalld package is installed (on RHEL).
  shell: yum list installed firewalld
  register: firewalld_installed
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Disable the firewalld service (on RHEL, if configured).
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat" and firewalld_installed.rc == 0

- name: Empty iptables rules
  shell: iptables -F
  when: ansible_os_family == "Debian"
